version: '3.8'

services:
  # ====================== DJANGO APP (deci_core) ======================
  core_django:
    build:
      context: ./deci_core
      dockerfile: Dockerfile
    container_name: core_app
    restart: unless-stopped
    env_file:
      - ./deci_core/.env
    environment:
      - SERVICE_ROLE=app
      - APP_ENV=${APP_ENV:-production}
      - DEBUG=${DEBUG:-False}
      # Django DB connection
      - POSTGRES_SERVER=core_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${CORE_POSTGRES_PORT:-5432}
      # FastAPI URL for cross-service calls
      - FASTAPI_URL=http://sirvan_garmsiri_app:8001
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
#      - ./deci_core/src:/app
    ports:
      - "8000:8000"
    depends_on:
      core_db:
        condition: service_healthy
    networks:
      - waplus_network

  core_db:
    image: postgres:15-alpine
    container_name: core_db
    restart: unless-stopped
    env_file:
      - ./deci_core/.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - core_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -q"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - waplus_network

  # ====================== FASTAPI APP (deci_sgwa) ======================
  sirvan_garmsiri_app:
    build:
      context: ./deci_sgwa
      dockerfile: Dockerfile
    container_name: sirvan_garmsiri_app
    restart: unless-stopped
    env_file:
      - ./deci_sgwa/.env
    environment:
      - SERVICE_ROLE=app
      - APP_ENV=${APP_ENV:-production}
      - DEBUG=${DEBUG:-False}
      # FastAPI DB connection (PostGIS)
      - POSTGRES_SERVER=waplus_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${WA_PLUS_POSTGRES_PORT:-5432}
      # Django URL for authentication
      - DJANGO_AUTH_URL=http://core_django:8000/api/auth/
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
#      - ./deci_sgwa/src:/app
    ports:
      - "8001:8001"
    depends_on:
      waplus_db:
        condition: service_healthy
    networks:
      - waplus_network

  waplus_db:
    image: postgis/postgis:15-3.3
    container_name: waplus_db
    restart: unless-stopped
    env_file:
      - ./deci_sgwa/.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - PGDATA=/var/lib/postgresql/data/pgdata # Explicitly setting PGDATA
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata # Mount for PGDATA
      - ./scripts/initdb:/docker-entrypoint-initdb.d # For initial DB setup scripts (e.g., creating extensions)
    ports:
      - "${POSTGRES_PORT_HOST:-5432}:5432" # Use POSTGRES_PORT_HOST from .env or default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -q"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - waplus_network

  # ====================== SHARED SERVICES ======================
  # GeoServer
  geoserver:
    image: kartoza/geoserver:2.23.0 # Using a specific version
    container_name: waplus_geoserver
    restart: unless-stopped
    env_file:
      - ./deci_sgwa/.env # Loads GEOSERVER_ADMIN_USER, GEOSERVER_ADMIN_PASSWORD etc.
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_EMAIL=${GEOSERVER_ADMIN_EMAIL:-geoserver@example.com}
      # GeoServer performance tuning (examples, adjust based on needs and resources)
      - MAX_MEMORY=1G # e.g., 1G, 2G
      - MIN_MEMORY=512M # e.g., 256M, 512M
      # Other GeoServer specific env vars from kartoza image:
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - ENABLE_JSONP=true
      - MAX_FILTER_RULES=20
      - OPTIMIZE_LINE_WIDTH=false
      - GEOSERVER_CSRF_WHITELIST=${APP_DOMAIN_NAME} # e.g. your.dashboard.com, if app is hosted and CSRF is enabled
    volumes:
      - geoserver_data:/opt/geoserver/data_dir # GeoServer's main data directory
      # - ./data/geoserver_data_dir_override:/opt/geoserver_override/data_dir # For specific overrides
      # - ./data/geoserver_webapp_override:/opt/geoserver_override/webapp # For webapp customizations
    ports:
      - "${GEOSERVER_PORT_HOST:-8080}:8080"
    depends_on:
      waplus_db: # GeoServer needs the database to be ready if it connects to PostGIS stores
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/geoserver/web/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give GeoServer more time to start up initially
    networks:
      - waplus_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: waplus_redis
    restart: unless-stopped
    # command: redis-server --requirepass ${REDIS_PASSWORD} # Uncomment if REDIS_PASSWORD is set
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT_HOST:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s # Reduced timeout, ping is fast
      retries: 5
    networks:
      - waplus_network

  # PGAdmin (optional, for database management)
  pgadmin:
    image: dpage/pgadmin4:latest # Or pin a version like 7.2
    container_name: waplus_pgadmin
    restart: unless-stopped
    env_file:
      - ./deci_sgwa/.env # Loads PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80 # pgAdmin listens on port 80 inside the container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      # You might want to mount a servers.json file to preconfigure DB connections
      # - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT_HOST:-5050}:80" # Host port maps to container's port 80
    depends_on:
      waplus_db:
        condition: service_healthy
    networks:
      - waplus_network


#   Traefik for reverse proxy (optional, advanced setup)
  traefik:
     image: traefik:v2.10
     container_name: waplus_traefik
     command:
       - --api.dashboard=true # Enable dashboard (be careful in prod, secure it)
       # - --api.insecure=true # For local dev dashboard access without auth
       - --log.level=DEBUG
       - --providers.docker=true
       - --providers.docker.exposedbydefault=false
       - --entrypoints.web.address=:80
       # - --entrypoints.websecure.address=:443 # For HTTPS
       # - --certificatesresolvers.myresolver.acme.tlschallenge=true # For Let's Encrypt
       # - --certificatesresolvers.myresolver.acme.email=your-email@example.com
       # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
     ports:
       - "80:80"   # HTTP
       - "443:443" # HTTPS (if configured)
       - "8081:8080" # Traefik dashboard (internal port 8080)
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro # Allow Traefik to listen to Docker events
       # - ./letsencrypt:/letsencrypt # Volume for Let's Encrypt certificates
     networks:
       - waplus_network
     labels: # Labels for Traefik itself if you want to access its dashboard via Traefik
       - "traefik.enable=true"
       - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)" # Example local hostname
       - "traefik.http.routers.traefik-dashboard.service=api@internal"
       - "traefik.http.routers.traefik-dashboard.entrypoints=web"
       # Add middleware for basic auth on dashboard in production
       # - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
       # - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$...$$..."


  # ====================== NETWORK DEFINITION ======================
networks:
  waplus_network:
    driver: bridge

volumes:
  core_postgres_data:
  waplus_postgres_data:
  static_volume:
  media_volume:
  postgres_data:
  geoserver_data:
  redis_data:
  pgadmin_data:
