"""measuement_category model added

Revision ID: 4267d2a77816
Revises: 6291d7ae561c
Create Date: 2025-06-01 07:00:13.331685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4267d2a77816'
down_revision = '6291d7ae561c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measurement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_of_measurement_categories_id'), 'unit_of_measurement_categories', ['id'], unique=False)
    op.create_index(op.f('ix_unit_of_measurement_categories_name'), 'unit_of_measurement_categories', ['name'], unique=True)
    op.drop_index(op.f('ix_cropping_patterns_id'), table_name='cropping_patterns')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_data_quality_flags_id'), table_name='data_quality_flags')
    op.drop_index(op.f('ix_financial_account_types_id'), table_name='financial_account_types')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_indicator_categories_id'), table_name='indicator_categories')
    op.drop_index(op.f('ix_indicator_definitions_id'), table_name='indicator_definitions')
    op.drop_index(op.f('ix_indicator_timeserieses_id'), table_name='indicator_timeserieses')
    op.drop_index(op.f('ix_infrastructure_types_id'), table_name='infrastructure_types')
    op.drop_index(op.f('ix_infrastructures_id'), table_name='infrastructures')
    op.drop_index(op.f('ix_operational_status_types_id'), table_name='operational_status_types')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_raster_metadatas_id'), table_name='raster_metadatas')
    op.drop_index(op.f('ix_reporting_unit_types_id'), table_name='reporting_unit_types')
    op.drop_index(op.f('ix_reporting_units_id'), table_name='reporting_units')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_temporal_resolutions_id'), table_name='temporal_resolutions')
    op.add_column('unit_of_measurements', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_unit_of_measurements_id'), table_name='unit_of_measurements')
    op.create_foreign_key(None, 'unit_of_measurements', 'unit_of_measurement_categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'unit_of_measurements', type_='foreignkey')
    op.create_index(op.f('ix_unit_of_measurements_id'), 'unit_of_measurements', ['id'], unique=False)
    op.drop_column('unit_of_measurements', 'category_id')
    op.create_index(op.f('ix_temporal_resolutions_id'), 'temporal_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_reporting_units_id'), 'reporting_units', ['id'], unique=False)
    op.create_index(op.f('ix_reporting_unit_types_id'), 'reporting_unit_types', ['id'], unique=False)
    op.create_index(op.f('ix_raster_metadatas_id'), 'raster_metadatas', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_operational_status_types_id'), 'operational_status_types', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructures_id'), 'infrastructures', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_types_id'), 'infrastructure_types', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_timeserieses_id'), 'indicator_timeserieses', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_definitions_id'), 'indicator_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_categories_id'), 'indicator_categories', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_account_types_id'), 'financial_account_types', ['id'], unique=False)
    op.create_index(op.f('ix_data_quality_flags_id'), 'data_quality_flags', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_index(op.f('ix_cropping_patterns_id'), 'cropping_patterns', ['id'], unique=False)
    op.drop_index(op.f('ix_unit_of_measurement_categories_name'), table_name='unit_of_measurement_categories')
    op.drop_index(op.f('ix_unit_of_measurement_categories_id'), table_name='unit_of_measurement_categories')
    op.drop_table('unit_of_measurement_categories')
    # ### end Alembic commands ###
