"""add_description_to_operational_status_type

Revision ID: 6291d7ae561c
Revises: 6f2a20bcfaa1
Create Date: 2025-05-27 07:33:10.878423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6291d7ae561c'
down_revision = '6f2a20bcfaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_status_types', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_status_types', 'description')
    # ### end Alembic commands ###
