"""initial_schema_vX

Revision ID: 63003f2a15fa
Revises: b91a83b5f0ba
Create Date: 2025-05-25 16:41:28.269186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63003f2a15fa'
down_revision = 'b91a83b5f0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cropping_patterns_id'), table_name='cropping_patterns')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_data_quality_flags_id'), table_name='data_quality_flags')
    op.drop_index(op.f('ix_financial_account_types_id'), table_name='financial_account_types')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_indicator_categories_id'), table_name='indicator_categories')
    op.drop_index(op.f('ix_indicator_definitions_id'), table_name='indicator_definitions')
    op.drop_index(op.f('ix_indicator_timeserieses_id'), table_name='indicator_timeserieses')
    op.drop_index(op.f('ix_infrastructure_types_id'), table_name='infrastructure_types')
    op.drop_index(op.f('ix_infrastructures_id'), table_name='infrastructures')
    op.drop_index(op.f('ix_operational_status_types_id'), table_name='operational_status_types')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_raster_metadatas_id'), table_name='raster_metadatas')
    op.drop_index(op.f('ix_reporting_unit_types_id'), table_name='reporting_unit_types')
    op.drop_index(op.f('ix_reporting_units_id'), table_name='reporting_units')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_temporal_resolutions_id'), table_name='temporal_resolutions')
    op.drop_index(op.f('ix_unit_of_measurements_id'), table_name='unit_of_measurements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_unit_of_measurements_id'), 'unit_of_measurements', ['id'], unique=False)
    op.create_index(op.f('ix_temporal_resolutions_id'), 'temporal_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_reporting_units_id'), 'reporting_units', ['id'], unique=False)
    op.create_index(op.f('ix_reporting_unit_types_id'), 'reporting_unit_types', ['id'], unique=False)
    op.create_index(op.f('ix_raster_metadatas_id'), 'raster_metadatas', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_operational_status_types_id'), 'operational_status_types', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructures_id'), 'infrastructures', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_types_id'), 'infrastructure_types', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_timeserieses_id'), 'indicator_timeserieses', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_definitions_id'), 'indicator_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_indicator_categories_id'), 'indicator_categories', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_account_types_id'), 'financial_account_types', ['id'], unique=False)
    op.create_index(op.f('ix_data_quality_flags_id'), 'data_quality_flags', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_index(op.f('ix_cropping_patterns_id'), 'cropping_patterns', ['id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
