"""add_description_to_infrastructure_type

Revision ID: 6f2a20bcfaa1
Revises: 63003f2a15fa
Create Date: 2025-05-27 07:20:15.841189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2a20bcfaa1'
down_revision = '63003f2a15fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_types', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infrastructure_types', 'description')
    # ### end Alembic commands ###
