"""add_unit_of_measurement_category_table_and_fk_to_unit_of_measurement

Revision ID: 98d98def6838
Revises: 6291d7ae561c
Create Date: 2025-05-31 14:01:11.814809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d98def6838'
down_revision = '6291d7ae561c' # Ensure this points to the actual previous migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measurement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_of_measurement_categories_name'), 'unit_of_measurement_categories', ['name'], unique=True)

    op.add_column('units_of_measurement', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_units_of_measurement_category_id_unit_of_measurement_categories', # Constraint name
        'units_of_measurement',             # Source table
        'unit_of_measurement_categories',   # Target table
        ['category_id'],                    # Source columns
        ['id']                              # Target columns
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_units_of_measurement_category_id_unit_of_measurement_categories', 'units_of_measurement', type_='foreignkey')
    op.drop_column('units_of_measurement', 'category_id')

    op.drop_index(op.f('ix_unit_of_measurement_categories_name'), table_name='unit_of_measurement_categories')
    op.drop_table('unit_of_measurement_categories')
    # ### end Alembic commands ###
